/**
 * Dev-only build step: turn the raw diceware word lists under wordlists/ into
 * typed, validated TypeScript modules under src/core/wordlists/.
 *
 * Both source files use the format "<dice-number>\t<word>"; we keep only the
 * word (the last whitespace token) and assert the list is exactly 7776 ASCII
 * lowercase words with no duplicates — anything else fails the build loudly.
 *
 * Run via:  npm run wordlists
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");

interface Source {
  readonly src: string;
  readonly out: string;
  readonly id: string;
  readonly attribution: string;
}

const SOURCES: readonly Source[] = [
  {
    src: "wordlists/eff_large_wordlist.txt",
    out: "src/core/wordlists/eff_large.ts",
    id: "eff_large",
    attribution: "EFF Large Wordlist (CC BY 3.0 US) — https://www.eff.org/dice",
  },
  {
    src: "wordlists/de-7776-v1-diceware.txt",
    out: "src/core/wordlists/de_7776.ts",
    id: "de_7776",
    attribution:
      "dys2p wordlists-de de-7776-v1 (CC0 / Unlicense / BSD-3) — https://github.com/dys2p/wordlists-de",
  },
];

function parseList(raw: string): string[] {
  return raw
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => line.length > 0)
    .map((line) => {
      const parts = line.split(/\s+/);
      return parts[parts.length - 1] ?? "";
    });
}

function validate(id: string, words: readonly string[]): void {
  if (words.length !== 7776) {
    throw new Error(`${id}: expected 7776 words, got ${words.length}`);
  }
  const seen = new Set<string>();
  for (const w of words) {
    // Lowercase ASCII a-z, optionally with internal hyphens (EFF has 4: drop-down,
    // felt-tip, t-shirt, yo-yo). The dys2p German list is pure a-z with no umlauts.
    if (!/^[a-z]+(?:-[a-z]+)*$/.test(w)) {
      throw new Error(`${id}: unexpected characters in word: ${JSON.stringify(w)}`);
    }
    if (w.length < 2 || w.length > 20) {
      throw new Error(`${id}: word length out of 2..20 range: ${JSON.stringify(w)}`);
    }
    if (seen.has(w)) throw new Error(`${id}: duplicate word: ${w}`);
    seen.add(w);
  }
}

function emit(s: Source, words: readonly string[]): void {
  const bitsPerWord = Math.log2(words.length);
  const header =
    `// AUTO-GENERATED by scripts/build-wordlists.ts — DO NOT EDIT.\n` +
    `// Source: ${s.attribution}\n` +
    `// ${words.length} words, ${bitsPerWord.toFixed(4)} bits/word.\n\n`;
  // Stored as a newline-joined string (compact source, fast parse) — safe because
  // every word is validated to be pure [a-z], so no backtick/${} escaping needed.
  const body = `export const words: readonly string[] = \`\n${words.join("\n")}\n\`.trim().split("\\n");\n`;
  const outPath = resolve(root, s.out);
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, header + body, "utf8");
  console.log(`✓ ${s.id}: ${words.length} words → ${s.out}`);
}

for (const s of SOURCES) {
  const raw = readFileSync(resolve(root, s.src), "utf8");
  const words = parseList(raw);
  validate(s.id, words);
  emit(s, words);
}
