/**
 * Post-build hardening (runs after `vite build`):
 *   1. Add Subresource Integrity (sha384) + crossorigin to the hashed assets in
 *      dist/index.html, and write dist/SRI.txt so a host can be verified.
 *   2. Generate a dependency-free service worker (dist/sw.js) that precaches every
 *      built asset for full offline / air-gapped use and never caches the HIBP API.
 *   3. Write dist/_headers (CSP + security headers) for Cloudflare Pages / Netlify.
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { createHash } from "node:crypto";
import { resolve, dirname, relative, join, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { buildHeadersFile } from "./security-headers";

const here = dirname(fileURLToPath(import.meta.url));
const dist = resolve(here, "..", "dist");

function sriFor(filePath: string): string {
  return "sha384-" + createHash("sha384").update(readFileSync(filePath)).digest("base64");
}

// 1) SRI on the index.html asset references -----------------------------------
const indexPath = resolve(dist, "index.html");
let html = readFileSync(indexPath, "utf8");
const sriLines: string[] = [];

html = html.replace(
  /<(script|link)\b([^>]*?)\s(src|href)="([^"]+)"([^>]*)>/g,
  (match: string, tag: string, pre: string, attr: string, url: string, post: string): string => {
    if (!url.includes("assets/")) return match;
    const rel = url.replace(/^\.?\//, "");
    let integrity: string;
    try {
      integrity = sriFor(resolve(dist, rel));
    } catch {
      return match;
    }
    sriLines.push(`${rel}  ${integrity}`);
    let attrs = `${pre} ${attr}="${url}"${post}`;
    if (!/\bintegrity=/.test(attrs)) attrs += ` integrity="${integrity}"`;
    if (!/\bcrossorigin/.test(attrs)) attrs += ` crossorigin="anonymous"`;
    return `<${tag}${attrs}>`;
  },
);
writeFileSync(indexPath, html, "utf8");
writeFileSync(resolve(dist, "SRI.txt"), sriLines.sort().join("\n") + "\n", "utf8");

// 2) Service worker -----------------------------------------------------------
function listFiles(dir: string): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir)) {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) out.push(...listFiles(full));
    else out.push("./" + relative(dist, full).split(sep).join("/"));
  }
  return out;
}

const EXCLUDE = new Set(["./sw.js", "./_headers", "./SRI.txt"]);
const assets = listFiles(dist)
  .filter((p) => !EXCLUDE.has(p))
  .sort();
const precache = ["./", ...assets];
const cacheVersion = "pwgen-" + createHash("sha256").update(precache.join("|")).digest("hex").slice(0, 10);

const sw = `// Auto-generated by scripts/postbuild.ts — do not edit.
const CACHE = ${JSON.stringify(cacheVersion)};
const ASSETS = ${JSON.stringify(precache, null, 0)};

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const url = new URL(event.request.url);
  // Never touch the opt-in breach-check API: let it go straight to the network.
  if (url.hostname === "api.pwnedpasswords.com") return;
  if (event.request.method !== "GET" || url.origin !== self.location.origin) return;
  event.respondWith(caches.match(event.request).then((hit) => hit || fetch(event.request)));
});
`;
writeFileSync(resolve(dist, "sw.js"), sw, "utf8");

// 3) Security headers ---------------------------------------------------------
writeFileSync(resolve(dist, "_headers"), buildHeadersFile(), "utf8");

console.log(`✓ postbuild: SRI for ${sriLines.length} asset(s), SW precache ${precache.length} file(s), _headers written.`);
