/**
 * Single source of truth for the Content-Security-Policy and HTTP security headers.
 *
 * Used by:
 *  - vite.config.ts        → injects the CSP as a <meta> tag at BUILD time
 *  - scripts/postbuild.ts  → writes dist/_headers (Cloudflare Pages / Netlify)
 *
 * The whole app is client-side; the ONLY external origin we ever talk to is the
 * opt-in Have-I-Been-Pwned range API. Everything else is locked to 'self'.
 */

export const CSP: string = [
  "default-src 'none'",
  "script-src 'self'",
  "style-src 'self'",
  "img-src 'self'",
  "font-src 'self'",
  "connect-src 'self' https://api.pwnedpasswords.com",
  "manifest-src 'self'",
  "worker-src 'self'",
  "base-uri 'none'",
  "form-action 'none'",
  "frame-ancestors 'none'",
  "upgrade-insecure-requests",
].join("; ");

export const SECURITY_HEADERS: Record<string, string> = {
  "Content-Security-Policy": CSP,
  "Strict-Transport-Security": "max-age=63072000; includeSubDomains; preload",
  "X-Content-Type-Options": "nosniff",
  "Referrer-Policy": "no-referrer",
  "X-Frame-Options": "DENY",
  "Cross-Origin-Opener-Policy": "same-origin",
  "Cross-Origin-Resource-Policy": "same-origin",
  "Permissions-Policy":
    "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()",
};

/** Build the Cloudflare Pages / Netlify `_headers` file content. */
export function buildHeadersFile(): string {
  const lines = ["# Generated by scripts/postbuild.ts — do not edit by hand.", "/*"];
  for (const [key, value] of Object.entries(SECURITY_HEADERS)) {
    lines.push(`  ${key}: ${value}`);
  }
  return lines.join("\n") + "\n";
}
